/**
 * 🤖 Smart Transit Hub: Route Analyzer Cron Job
 * 
 * Purpose: This script analyzes the last 30 days of driver location data (TrajectoryMatcher / LocationLogs),
 * finds patterns, and automatically generates 'DailySchedules' for the Smart Transit Hub widget.
 * 
 * Logic:
 * 1. Fetch completed trips/logs for the past 30 days grouped by driver.
 * 2. Identify if a driver crosses a specific zone at roughly the same time (± 15 mins) > 20 days/month.
 * 3. If a pattern is detected, insert/update a 'DailySchedule' with isAutoGenerated: true.
 */

import mongoose from 'mongoose';
import { DailySchedule } from '../models/ussModels.js';
import { User, TripLog } from '../models.js'; // Assuming TripLog or similar exists
import cron from 'node-cron';

// Configuration
const PATTERN_THRESHOLD_DAYS = 20; // Needs to be seen 20 times in a month
const TIME_WINDOW_MINUTES = 15; // ± 15 minutes variance allowed

export const analyzeDrivingPatterns = async () => {
    console.log('[AI Route Analyzer] Starting 30-day historical pattern analysis...');
    
    try {
        const thirtyDaysAgo = new Date();
        thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

        // Fetch all drivers
        const drivers = await User.find({ role: 'DRIVER', isActive: true }, 'id vehicleType').lean();
        let newSchedulesCount = 0;

        for (const driver of drivers) {
            // STEP 1: Fetch historical location data for this driver
            // Note: Replace 'TripLog' with your actual historical location log collection if different
            const logs = await mongoose.connection.db.collection('locationlogs').find({
                driverId: driver.id,
                timestamp: { $gte: thirtyDaysAgo }
            }).toArray();

            if (logs.length < PATTERN_THRESHOLD_DAYS) continue;

            // STEP 2: Group logs by geospatial clusters (approx 1km grids)
            // For simplicity in this script, we'll bucket by rough Lat/Lng coordinates (rounded to 2 decimals ≈ 1.1km)
            const clusters = {};
            
            logs.forEach(log => {
                if (!log.location || !log.location.coordinates) return;
                const [lng, lat] = log.location.coordinates;
                const roundedLat = lat.toFixed(2);
                const roundedLng = lng.toFixed(2);
                const clusterKey = `${roundedLat},${roundedLng}`;

                // Extract time of day (HH:MM)
                const date = new Date(log.timestamp);
                const timeKey = `${String(date.getHours()).padStart(2, '0')}:${String(Math.floor(date.getMinutes() / TIME_WINDOW_MINUTES) * TIME_WINDOW_MINUTES).padStart(2, '0')}`;

                if (!clusters[clusterKey]) clusters[clusterKey] = {};
                if (!clusters[clusterKey][timeKey]) clusters[clusterKey][timeKey] = new Set();
                
                // Track unique days this cluster+time combo was hit
                clusters[clusterKey][timeKey].add(date.toDateString());
            });

            // STEP 3: Evaluate Patterns
            for (const [clusterKey, timeGroups] of Object.entries(clusters)) {
                for (const [timeKey, uniqueDaysSet] of Object.entries(timeGroups)) {
                    const hitCount = uniqueDaysSet.size;

                    // If driver hits this 1km zone at this specific time >= 20 days a month, it's a routine!
                    if (hitCount >= PATTERN_THRESHOLD_DAYS) {
                        const [latStr, lngStr] = clusterKey.split(',');
                        const confidence = Math.round((hitCount / 30) * 100);

                        // Upsert the Daily Schedule
                        await DailySchedule.findOneAndUpdate(
                            {
                                driverId: driver.id,
                                expectedTime: timeKey,
                                isAutoGenerated: true,
                                'location.coordinates': [parseFloat(lngStr), parseFloat(latStr)]
                            },
                            {
                                $set: {
                                    id: `AI-SCH-${driver.id}-${Date.now()}`,
                                    driverId: driver.id,
                                    vehicleType: driver.vehicleType || 'BUS',
                                    stopName: 'AI Predicted Stop', // Can reverse-geocode here if needed
                                    destination: 'Regular Route',
                                    expectedTime: timeKey,
                                    isAutoGenerated: true,
                                    confidenceScore: confidence,
                                    location: {
                                        type: 'Point',
                                        coordinates: [parseFloat(lngStr), parseFloat(latStr)]
                                    }
                                }
                            },
                            { upsert: true, new: true }
                        );
                        newSchedulesCount++;
                    }
                }
            }
        }
        
        console.log(`[AI Route Analyzer] Completed. Generated/Updated ${newSchedulesCount} AI Schedules based on 30-day patterns.`);

    } catch (error) {
        console.error('[AI Route Analyzer] Error during analysis:', error);
    }
};

// Initialize Cron Job (Runs every Sunday at 3:00 AM)
export const initRouteAnalyzerCron = () => {
    // '0 3 * * 0' = Every Sunday at 03:00 AM
    cron.schedule('0 3 * * 0', () => {
        analyzeDrivingPatterns();
    });
    console.log('🤖 AI Route Analyzer Cron Scheduled: Running weekly on Sundays at 03:00 AM');
};
