/**
 * Dashboard Routes — Unified role-based dashboards
 * 
 * Single API call per role returns all relevant data
 */

import express from 'express';
import { User, Ticket, DriverLocation, CropListing, ProcurementOrder, FoodOrder, Parcel, Notification } from '../models.js';
import { DailySchedule } from '../models/ussModels.js';
import { findMatchingVehicles } from '../services/trajectoryMatcher.js';
import * as Auth from '../auth.js';

const router = express.Router();

/**
 * GET /api/dashboard/transit-hub
 * Smart Transit Hub Widget Data source (Live + Scheduled)
 */
router.get('/transit-hub', Auth.authenticate, async (req, res) => {
    try {
        const { lat, lng } = req.query;
        if (!lat || !lng) {
            return res.status(400).json({ error: 'Coordinates required' });
        }

        const userLat = parseFloat(lat);
        const userLng = parseFloat(lng);

        // Use token payload directly to identify the demo user
        const isDemoUser = req.user && req.user.phone === '9801615895';

        // 1. Live Vehicles (Using Phase 5 Trajectory Matcher - active memory)
        let liveVehicles = [];
        try {
            // Find nearby vehicles by querying a tiny 0.01 degree path
            const rawLiveMatches = findMatchingVehicles(userLat, userLng, userLat + 0.01, userLng + 0.01, 5.0);
            
            liveVehicles = rawLiveMatches.slice(0, 5).map((match, idx) => ({
                id: match.driverId || `live-${idx}`,
                type: match.vehicleType || 'Bus',
                destination: match.endLocationName || 'Terminal',
                seats: match.availableSeats || 0,
                distance: match.snappedDistanceKm ? `${match.snappedDistanceKm.toFixed(1)} km` : 'Near',
                eta: match.etaMins ? `${Math.round(match.etaMins)} min` : 'Live'
            }));
        } catch (e) {
            console.error('Trajectory Matcher Error:', e.message);
        }

        // 2. Daily Scheduled Passes (MongoDB Geospatial Query)
        let formattedSchedules = [];
        try {
            const scheduledVehicles = await DailySchedule.find({
                location: {
                    $near: {
                        $geometry: { type: "Point", coordinates: [userLng, userLat] },
                        $maxDistance: 5000 // 5km
                    }
                }
            }).limit(5).lean();

            formattedSchedules = scheduledVehicles.map(s => ({
                id: s.id || s._id.toString(),
                time: s.expectedTime,
                vehicle: `${s.vehicleType || 'Bus'} (${s.destination || s.stopName})`,
                type: s.isAutoGenerated ? 'AI_PREDICTED' : 'MANUAL',
                confidence: s.confidenceScore || 100
            }));
        } catch (dbErr) {
            console.error('DailySchedule DB Error:', dbErr.message);
        }

        if (isDemoUser && liveVehicles.length === 0) {
            liveVehicles = [
                { id: 'mock-1', type: 'Bus', destination: 'Patna Junction', seats: 12, distance: '1.2 km', eta: '5 min' },
                { id: 'mock-2', type: 'Cab', destination: 'Sasaram City', seats: 3, distance: '800 m', eta: '2 min' }
            ];
        }

        if (isDemoUser && formattedSchedules.length === 0) {
            formattedSchedules = [
                { id: 'mock-s1', time: '08:30 AM', vehicle: 'Express Bus (Buxar)', type: 'AI_PREDICTED', confidence: 92 },
                { id: 'mock-s2', time: '10:00 AM', vehicle: 'Shared Auto (Market)', type: 'MANUAL', confidence: 100 }
            ];
        }

        res.json({
            live: liveVehicles,
            scheduled: formattedSchedules
        });

    } catch (error) {
        console.error('Transit Hub Error:', error);
        res.status(500).json({ error: 'Failed to load transit data' });
    }
});

/**
 * GET /api/dashboard
 * Returns dashboard data based on user's role
 */
router.get('/', Auth.authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const user = await User.findOne({ id: userId }).lean();
    if (!user) return res.status(404).json({ error: 'User not found' });

    const role = user.role;
    const now = new Date();
    const startOfDay = new Date(now); startOfDay.setHours(0, 0, 0, 0);

    // Common: unread notifications
    const unreadNotifications = await Notification.countDocuments({ userId, isRead: false });
    const recentNotifications = await Notification.find({ userId }).sort({ createdAt: -1 }).limit(5).lean();

    let dashboardData = { role, unreadNotifications, recentNotifications };

    switch (role) {
      case 'PASSENGER': {
        const [activeTickets, totalTickets] = await Promise.all([
          Ticket.find({ userId, status: { $in: ['PENDING', 'PAID', 'BOARDED'] } }).lean(),
          Ticket.countDocuments({ userId })
        ]);
        dashboardData = {
          ...dashboardData,
          activeTickets,
          totalTrips: totalTickets,
          walletBalance: user.walletBalance || 0
        };
        break;
      }

      case 'DRIVER': {
        const [location, todayTickets, totalTrips] = await Promise.all([
          DriverLocation.findOne({ driverId: userId }).lean(),
          Ticket.find({ scannedByDriverId: userId, scannedAt: { $gte: startOfDay.getTime() } }).lean(),
          Ticket.countDocuments({ scannedByDriverId: userId })
        ]);

        const todayEarnings = todayTickets.reduce((s, t) => s + (t.totalPrice || 0), 0);
        const todayPassengers = todayTickets.reduce((s, t) => s + (t.passengerCount || 1), 0);
        const autoVerified = todayTickets.filter(t => t.verificationMethod === 'GPS_SPEED_MATCH').length;

        const pendingDeliveries = await ProcurementOrder.countDocuments({
          assignedDriverId: userId,
          status: { $in: ['DRIVER_ASSIGNED', 'PICKED_UP'] }
        }).catch(() => 0);

        dashboardData = {
          ...dashboardData,
          isOnline: location?.isOnline || false,
          activeRoute: location?.activeRouteName,
          seats: location ? {
            total: location.seatsTotal || 20,
            occupied: location.seatsOccupied || 0,
            available: (location.seatsTotal || 20) - (location.seatsOccupied || 0)
          } : null,
          today: { earnings: todayEarnings, passengers: todayPassengers, trips: todayTickets.length, autoVerified },
          totalTrips,
          pendingDeliveries
        };
        break;
      }

      case 'FARMER': {
        const [activeListings, orders, deliveredOrders] = await Promise.all([
          CropListing.countDocuments({ kisanId: userId, status: 'ACTIVE' }),
          ProcurementOrder.find({ kisanId: userId }).sort({ createdAt: -1 }).limit(5).lean(),
          ProcurementOrder.find({ kisanId: userId, status: 'DELIVERED' }).lean()
        ]);

        const totalEarnings = deliveredOrders.reduce((s, o) => s + (o.totalAmount || 0), 0);

        dashboardData = {
          ...dashboardData,
          activeListings,
          recentOrders: orders,
          totalEarnings,
          pendingOrders: orders.filter(o => o.status === 'PLACED').length
        };
        break;
      }

      case 'SHOPKEEPER':
      case 'FOOD_VENDOR': {
        const todayOrders = await FoodOrder.find({
          vendorId: userId,
          createdAt: { $gte: startOfDay.getTime() }
        }).lean().catch(() => []);

        const todayRevenue = todayOrders.reduce((s, o) => s + (o.totalPrice || 0), 0);

        dashboardData = {
          ...dashboardData,
          todayOrders: todayOrders.length,
          todayRevenue,
          pendingOrders: todayOrders.filter(o => ['PLACED', 'ACCEPTED', 'PREPARING'].includes(o.status)).length,
          completedOrders: todayOrders.filter(o => o.status === 'DELIVERED').length
        };
        break;
      }

      default: {
        dashboardData = { ...dashboardData, message: 'Dashboard available for specific roles' };
      }
    }

    res.json(dashboardData);
  } catch (error) {
    console.error('Dashboard error:', error);
    res.status(500).json({ error: 'Failed to load dashboard' });
  }
});

/**
 * GET /api/dashboard/notifications
 * Get paginated notifications
 */
router.get('/notifications', Auth.authenticate, async (req, res) => {
  try {
    const { limit, skip } = req.query;
    const notifications = await Notification.find({ userId: req.user.id })
      .sort({ createdAt: -1 })
      .skip(parseInt(skip) || 0)
      .limit(parseInt(limit) || 20)
      .lean();

    const unread = await Notification.countDocuments({ userId: req.user.id, isRead: false });

    res.json({ notifications, unread, total: notifications.length });
  } catch (error) {
    res.status(500).json({ error: 'Failed to get notifications' });
  }
});

/**
 * PUT /api/dashboard/notifications/read-all
 */
router.put('/notifications/read-all', Auth.authenticate, async (req, res) => {
  try {
    await Notification.updateMany({ userId: req.user.id, isRead: false }, { isRead: true });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
